### ISSUE TITLE
Docker compose up is failing

### ISSUE THREAD

**Issue by msusicky** [opendatalabcz/traffic-surveys-automation#18]
docker compose up built everything but after start...
```
tsa-database  | The files belonging to this database system will be owned by user "postgres".
tsa-database  | This user must also own the server process.
tsa-database  |
tsa-database  | The database cluster will be initialized with locale "en_US.utf8".
tsa-database  | The default database encoding has accordingly been set to "UTF8".
tsa-database  | The default text search configuration will be set to "english".
tsa-database  |
tsa-database  | Data page checksums are disabled.
tsa-database  |
tsa-database  | fixing permissions on existing directory /var/lib/postgresql/data ... initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
tsa-database exited with code 1```

**Comment by ondrejpudis** [comment]
Did you create the necessary folders? Maybe if the `../postgres_data` does not exist or it is not allowed to write there, you face this issue.

I've updated the thesis text in this way but the README states that the four folders are necessary.

Probably I was too quick to stay that only `docker-compose up` is sufficient to start the whole thing.

**Comment by msusicky** [comment]
Not in the first try, but then yes. The trouble here is that I'm running it in WSL2. Trick is to move git repository out of /mnt directory to /home/... so native WSL can be used and owner changed to postgres :)
