### ISSUE TITLE
Tests should not contain fixed paths to your local disk 

### ISSUE THREAD

**Issue by msusicky** [opendatalabcz/traffic-surveys-automation#19]
https://github.com/opendatalabcz/traffic-surveys-automation/blob/f13da2a8673b969b17faf4029c4d6b706ea13625/backend/test/integration/test_deep_sort.py#L8

**Comment by ondrejpudis** [comment]
I completely forgot about that. I'll try to remove and replace it with a small portion of the data available as part of the tests folder.
