### ISSUE TITLE
Don't use Git LFS

### ISSUE THREAD

**Issue by msusicky** [opendatalabcz/traffic-surveys-automation#8]
You exceeded limit of 1GB for Git LFS -> dont store models in the repo, save them somewhere else and download them via build.
Thanks :)

**Comment by ondrejpudis** [comment]
I hoped that we could have the tar.gz versions versioned and kept as a part of the final repo, but if it exceeds the quota, I remove them from the repo (not sure how to remove them from the git history, I don't want to force-push master).

Also not sure if downloading them during the build is a good idea, even the image itself is quite huge (more than 3GB), adding the models would increase the size even more. I was rather thinking of downloading them the first time they are needed during execution.

I'd address this later when we're building the complete backend application.
